# configure topics of interest

Interested Topics:
    - Hash Table
    - Array
    - Probability and Statistics
    - Math
    - String
    - Sliding Window
    - Divide and Conquer
    - Two Pointers
    - String Matching
    - Matrix
    - Simulation
    - Geometry
    - Interactive
    - Database
    - Hash Function
    - Prefix Sum
    - Brainteaser
    - Greedy

Skip Topics:
  - Binary Search
  - Recursion
  - Linked List
  - Dynamic Programming
  - Trie
  - Sorting
  - Backtracking
  - Stack
  - Merge Sort
  - Heap (Priority Queue)
  - Bit Manipulation
  - Monotonic Stack
  - Combinatorics
  - Memoization
  - Depth-First Search
  - Binary Tree
  - Tree
  - Binary Search Tree
  - Breadth-First Search
  - Union Find
  - Graph
  - Design
  - Doubly-Linked List
  - Radix Sort
  - Bucket Sort
  - Counting
  - Data Stream
  - Iterator
  - Rolling Hash
  - Shell
  - Enumeration
  - Number Theory
  - Topological Sort
  - Quickselect
  - Line Sweep
  - Binary Indexed Tree
  - Ordered Set
  - Segment Tree
  - Queue
  - Monotonic Queue
  - Counting Sort
  - Game Theory
  - Eulerian Circuit
  - Bitmask
  - Randomized
  - Reservoir Sampling
  - Shortest Path
  - Rejection Sampling
  - Suffix Array
  - Concurrency
  - Minimum Spanning Tree
  - Biconnected Component
  - Strongly Connected Component